version: 2
updates:

- package-ecosystem: "pip"
  directory: "/.github/actions/pr_notifier"
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/configs"
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/test/extensions/filters/network/thrift_proxy"
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/examples/grpc-bridge/client"
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/tools/base"
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/tools/code_format"
  schedule:
    interval: "daily"

- package-ecosystem: "pip"
  directory: "/tools/dependency"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/ci"
  schedule:
    interval: daily

- package-ecosystem: "docker"
  directory: "/.devcontainer"
  schedule:
    interval: daily

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
